name: kbrashears5-3

on:
  push:
    branches:
      - master
  schedule:
    - cron: 15 * * * *

jobs:
  kbrashears5-3:
    runs-on: ubuntu-latest
    steps:
      - name: On Ubuntu
        uses: actions/checkout@master
      # File Sync
      - name: File Sync Started
        uses: kbrashears5/github-action-file-sync@master
        with:
          REPOSITORIES: |
            TheBoringWebsites/bddummy2
            TheBoringWebsites/bddummy3
          FILES: |
            /templates=3/
            LICENSE=LICENSE
          TOKEN: ${{ secrets.FILE_SYNC_TOKEN }}
