# This simply syncs only workflows in ".github/workflows",no custom destination folder is supported.
# No support for reading every file in a folder and simply copy pasting it in destination.

name: Varun-2
on:
  push:
    branches:
      - master
env:
  DRY_RUN: false
  REPOSITORIES: |
            TheBoringWebsites/bddummy2
            TheBoringWebsites/bddummy3
  
  
  WORKFLOW_FILES: |
            # 
            ./templates/Mac-Mas-Mas.yml
            ./templates/Mac-Dev-Mas.yml
            ./templates/Mac-Dev-Dev.yml
            ./templates/Win-Mas-Mas.yml
            ./templates/Win-Dev-Mas.yml
            ./templates/Win-Dev-Dev.yml
            ./templates/Ubu-Mas-Mas.yml
            ./templates/Ubu-Dev-Mas.yml
            ./templates/Ubu-Dev-Dev.yml
            ./templates/Multi-CI-tic-Mas-Mas.yml
            ./templates/Multi-CI-tic-Dev-Mas.yml
            ./templates/Multi-CI-tidyverse-Mas-Mas.yml


jobs:
  Varun-2:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@master
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.FILE_SYNC_TOKEN }}
