name: Workflow Sync

on:
  push:
    branches:
      - master
env:
  DRY_RUN: false
  REPOSITORIES: |
            TheBoringWebsites/bddummy2
            TheBoringWebsites/bddummy3
  
  
  WORKFLOW_FILES: |
            ./templates/*=.github/workflows/
            LICENSE=LICENSE
            #./templates/Mac-Dev-Dev.yml=.github/workflows/
            #./templates/*.yml=.github/workflows/

jobs:
  Varun-Solution:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@master
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.FILE_SYNC_TOKEN }}
