name: Varun-2

on:
  push:
    branches:
      - master
env:
  DRY_RUN: false
  REPOSITORIES: |
            TheBoringWebsites/bddummy2
            TheBoringWebsites/bddummy3
  
  
  WORKFLOW_FILES: |
            # trying if folders can be copied
            #./templates/*=./2
            #LICENSE=LICENSE
            # with direct file name it works
            ./templates/Mac-Dev-Dev.yml= ./2
            #./templates/*.yml=/2

jobs:
  Varun-2:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Local Repository
        uses: actions/checkout@master
      - name: Running Workflow Sync
        uses: varunsridharan/action-github-workflow-sync@master
        with:
          DRY_RUN: ${{ env.DRY_RUN }}
          REPOSITORIES: ${{ env.REPOSITORIES }}
          WORKFLOW_FILES: ${{ env.WORKFLOW_FILES }}
          GITHUB_TOKEN: ${{ secrets.FILE_SYNC_TOKEN }}
